# Form implementation generated from reading ui file '.\res\frmDlgNeoRecConnection.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DlgNeoRecConnection(object):
    def setupUi(self, DlgNeoRecConnection):
        DlgNeoRecConnection.setObjectName("DlgNeoRecConnection")
        DlgNeoRecConnection.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        DlgNeoRecConnection.resize(354, 208)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=DlgNeoRecConnection)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 331, 101))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=DlgNeoRecConnection)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 130, 331, 71))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)

        self.retranslateUi(DlgNeoRecConnection)
        QtCore.QMetaObject.connectSlotsByName(DlgNeoRecConnection)

    def retranslateUi(self, DlgNeoRecConnection):
        _translate = QtCore.QCoreApplication.translate
        DlgNeoRecConnection.setWindowTitle(_translate("DlgNeoRecConnection", "Dialog"))
        self.label.setText(_translate("DlgNeoRecConnection", "TextLabel"))
        self.label_2.setText(_translate("DlgNeoRecConnection", "TextLabel"))
