# Form implementation generated from reading ui file '.\res\frmDialogSelectAmp.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SelectAmps(object):
    def setupUi(self, SelectAmps):
        SelectAmps.setObjectName("SelectAmps")
        SelectAmps.resize(445, 377)
        self.verticalLayout = QtWidgets.QVBoxLayout(SelectAmps)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=SelectAmps)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.groupBox = QtWidgets.QGroupBox(parent=SelectAmps)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.radioButtonActicPlus = QtWidgets.QRadioButton(parent=self.groupBox)
        self.radioButtonActicPlus.setObjectName("radioButtonActicPlus")
        self.gridLayout.addWidget(self.radioButtonActicPlus, 0, 0, 1, 1)
        self.radioButtonActic2 = QtWidgets.QRadioButton(parent=self.groupBox)
        self.radioButtonActic2.setObjectName("radioButtonActic2")
        self.gridLayout.addWidget(self.radioButtonActic2, 1, 0, 1, 1)
        self.radioButtonNeoRec = QtWidgets.QRadioButton(parent=self.groupBox)
        self.radioButtonNeoRec.setObjectName("radioButtonNeoRec")
        self.gridLayout.addWidget(self.radioButtonNeoRec, 2, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=SelectAmps)
        self.buttonBox.setEnabled(True)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(SelectAmps)
        self.buttonBox.accepted.connect(SelectAmps.accept) # type: ignore
        self.buttonBox.rejected.connect(SelectAmps.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SelectAmps)

    def retranslateUi(self, SelectAmps):
        _translate = QtCore.QCoreApplication.translate
        SelectAmps.setWindowTitle(_translate("SelectAmps", "Dialog"))
        self.label.setText(_translate("SelectAmps", "Welcome to PyCorderPlus!"))
        self.groupBox.setTitle(_translate("SelectAmps", "Select Amplifier Type"))
        self.radioButtonActicPlus.setText(_translate("SelectAmps", "ActiCHamp Plus"))
        self.radioButtonActic2.setText(_translate("SelectAmps", "ActiCHamp2"))
        self.radioButtonNeoRec.setText(_translate("SelectAmps", "NeoRec (NeoRec cap, NeoRec 21)"))
