# Form implementation generated from reading ui file '.\res\frmImpedanceDisplay.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_frmImpedanceDisplay(object):
    def setupUi(self, frmImpedanceDisplay):
        frmImpedanceDisplay.setObjectName("frmImpedanceDisplay")
        frmImpedanceDisplay.resize(1100, 744)
        frmImpedanceDisplay.setSizeGripEnabled(True)
        self.gridLayout_2 = QtWidgets.QGridLayout(frmImpedanceDisplay)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tableWidgetValues = QtWidgets.QTableWidget(parent=frmImpedanceDisplay)
        self.tableWidgetValues.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tableWidgetValues.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.NoSelection)
        self.tableWidgetValues.setRowCount(16)
        self.tableWidgetValues.setColumnCount(10)
        self.tableWidgetValues.setObjectName("tableWidgetValues")
        self.tableWidgetValues.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidgetValues.horizontalHeader().setDefaultSectionSize(70)
        self.tableWidgetValues.horizontalHeader().setHighlightSections(True)
        self.tableWidgetValues.horizontalHeader().setMinimumSectionSize(10)
        self.tableWidgetValues.verticalHeader().setDefaultSectionSize(40)
        self.gridLayout_2.addWidget(self.tableWidgetValues, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.groupBoxRange = QtWidgets.QGroupBox(parent=frmImpedanceDisplay)
        self.groupBoxRange.setObjectName("groupBoxRange")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBoxRange)
        self.gridLayout.setObjectName("gridLayout")
        self.ScaleWidget = QwtScaleWidget(self.groupBoxRange)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ScaleWidget.sizePolicy().hasHeightForWidth())
        self.ScaleWidget.setSizePolicy(sizePolicy)
        self.ScaleWidget.setMinimumSize(QtCore.QSize(80, 0))
        self.ScaleWidget.setObjectName("ScaleWidget")
        self.gridLayout.addWidget(self.ScaleWidget, 0, 0, 1, 1)
        self.checkBoxValues = QtWidgets.QCheckBox(parent=self.groupBoxRange)
        self.checkBoxValues.setObjectName("checkBoxValues")
        self.gridLayout.addWidget(self.checkBoxValues, 3, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.groupBoxRange)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.comboBoxRange = QtWidgets.QComboBox(parent=self.groupBoxRange)
        self.comboBoxRange.setEditable(True)
        self.comboBoxRange.setInsertPolicy(QtWidgets.QComboBox.InsertPolicy.NoInsert)
        self.comboBoxRange.setObjectName("comboBoxRange")
        self.comboBoxRange.addItem("")
        self.comboBoxRange.addItem("")
        self.comboBoxRange.addItem("")
        self.comboBoxRange.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBoxRange)
        self.label_2 = QtWidgets.QLabel(parent=self.groupBoxRange)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBoxRange)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 1, 1, 1)

        self.retranslateUi(frmImpedanceDisplay)
        QtCore.QMetaObject.connectSlotsByName(frmImpedanceDisplay)

    def retranslateUi(self, frmImpedanceDisplay):
        _translate = QtCore.QCoreApplication.translate
        frmImpedanceDisplay.setWindowTitle(_translate("frmImpedanceDisplay", "Impedance"))
        self.groupBoxRange.setTitle(_translate("frmImpedanceDisplay", "Range [KOhm]"))
        self.checkBoxValues.setText(_translate("frmImpedanceDisplay", "Show Values"))
        self.label.setText(_translate("frmImpedanceDisplay", "0 - "))
        self.comboBoxRange.setItemText(0, _translate("frmImpedanceDisplay", "5"))
        self.comboBoxRange.setItemText(1, _translate("frmImpedanceDisplay", "20"))
        self.comboBoxRange.setItemText(2, _translate("frmImpedanceDisplay", "50"))
        self.comboBoxRange.setItemText(3, _translate("frmImpedanceDisplay", "100"))
        self.label_2.setText(_translate("frmImpedanceDisplay", "KOhm"))
from qwt.scale_widget import QwtScaleWidget
