# Form implementation generated from reading ui file '.\res\frmLogView.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_frmLogView(object):
    def setupUi(self, frmLogView):
        frmLogView.setObjectName("frmLogView")
        frmLogView.resize(880, 400)
        self.gridLayout = QtWidgets.QGridLayout(frmLogView)
        self.gridLayout.setObjectName("gridLayout")
        self.labelView = QtWidgets.QPlainTextEdit(parent=frmLogView)
        self.labelView.setLineWrapMode(QtWidgets.QPlainTextEdit.LineWrapMode.NoWrap)
        self.labelView.setReadOnly(True)
        self.labelView.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.labelView.setBackgroundVisible(False)
        self.labelView.setObjectName("labelView")
        self.gridLayout.addWidget(self.labelView, 0, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButtonSave = QtWidgets.QPushButton(parent=frmLogView)
        self.pushButtonSave.setAutoDefault(False)
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.horizontalLayout.addWidget(self.pushButtonSave)
        self.pushButtonClose = QtWidgets.QPushButton(parent=frmLogView)
        self.pushButtonClose.setDefault(True)
        self.pushButtonClose.setObjectName("pushButtonClose")
        self.horizontalLayout.addWidget(self.pushButtonClose)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 1, 1, 1)

        self.retranslateUi(frmLogView)
        self.pushButtonClose.clicked.connect(frmLogView.reject) # type: ignore
        self.pushButtonSave.clicked.connect(frmLogView.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(frmLogView)

    def retranslateUi(self, frmLogView):
        _translate = QtCore.QCoreApplication.translate
        frmLogView.setWindowTitle(_translate("frmLogView", "Log History"))
        self.pushButtonSave.setText(_translate("frmLogView", "Save"))
        self.pushButtonClose.setText(_translate("frmLogView", "Close"))
