# Form implementation generated from reading ui file '.\res\frmMainConfiguration.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from importlib.resources import path
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_frmConfiguration(object):
    def setupUi(self, frmConfiguration):
        frmConfiguration.setObjectName("frmConfiguration")
        frmConfiguration.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        frmConfiguration.resize(861, 743)
        icon = QtGui.QIcon()
        with path("res", "process.png") as f_path:
            icon.addPixmap(QtGui.QPixmap(str(f_path)), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        frmConfiguration.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(frmConfiguration)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(parent=frmConfiguration)
        self.tabWidget.setObjectName("tabWidget")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.gridLayout1 = QtWidgets.QGridLayout(self.tab1)
        self.gridLayout1.setObjectName("gridLayout1")
        self.tabWidget.addTab(self.tab1, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=frmConfiguration)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(frmConfiguration)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(frmConfiguration.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(frmConfiguration)

    def retranslateUi(self, frmConfiguration):
        _translate = QtCore.QCoreApplication.translate
        frmConfiguration.setWindowTitle(_translate("frmConfiguration", "Configuration"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("frmConfiguration", "Tab 1"))

