# Form implementation generated from reading ui file '.\res\frmNeoRecOnline.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from importlib.resources import path
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_frmNeoRecOnline(object):
    def setupUi(self, frmNeoRecOnline):
        frmNeoRecOnline.setObjectName("frmNeoRecOnline")
        frmNeoRecOnline.resize(427, 233)
        frmNeoRecOnline.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        frmNeoRecOnline.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.gridLayout_3 = QtWidgets.QGridLayout(frmNeoRecOnline)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBoxMode = QtWidgets.QGroupBox(parent=frmNeoRecOnline)
        self.groupBoxMode.setFlat(False)
        self.groupBoxMode.setCheckable(False)
        self.groupBoxMode.setObjectName("groupBoxMode")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBoxMode)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonStartDefault = QtWidgets.QPushButton(parent=self.groupBoxMode)
        self.pushButtonStartDefault.setMinimumSize(QtCore.QSize(100, 40))
        self.pushButtonStartDefault.setStyleSheet("text-align: left; padding-left: 10px;")
        icon = QtGui.QIcon()
        with path("res", "play.png") as f_path:
            icon.addPixmap(QtGui.QPixmap(str(f_path)), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        with path("res", "play_green.png") as f_path:
            icon.addPixmap(QtGui.QPixmap(str(f_path)), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.pushButtonStartDefault.setIcon(icon)
        self.pushButtonStartDefault.setIconSize(QtCore.QSize(32, 32))
        self.pushButtonStartDefault.setCheckable(True)
        self.pushButtonStartDefault.setAutoExclusive(True)
        self.pushButtonStartDefault.setAutoDefault(False)
        self.pushButtonStartDefault.setObjectName("pushButtonStartDefault")
        self.horizontalLayout.addWidget(self.pushButtonStartDefault)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.pushButtonStop = QtWidgets.QPushButton(parent=self.groupBoxMode)
        self.pushButtonStop.setMinimumSize(QtCore.QSize(100, 40))
        icon1 = QtGui.QIcon()
        with path("res", "stop.png") as f_path:
            icon1.addPixmap(QtGui.QPixmap(str(f_path)), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        with path("res", "stop_green.png") as f_path:
            icon1.addPixmap(QtGui.QPixmap(str(f_path)), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.pushButtonStop.setIcon(icon1)
        self.pushButtonStop.setIconSize(QtCore.QSize(32, 32))
        self.pushButtonStop.setCheckable(True)
        self.pushButtonStop.setAutoExclusive(True)
        self.pushButtonStop.setObjectName("pushButtonStop")
        self.gridLayout.addWidget(self.pushButtonStop, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButtonStartImpedance = QtWidgets.QPushButton(parent=self.groupBoxMode)
        self.pushButtonStartImpedance.setMinimumSize(QtCore.QSize(100, 40))
        self.pushButtonStartImpedance.setIcon(icon)
        self.pushButtonStartImpedance.setIconSize(QtCore.QSize(32, 32))
        self.pushButtonStartImpedance.setCheckable(True)
        self.pushButtonStartImpedance.setAutoExclusive(True)
        self.pushButtonStartImpedance.setAutoDefault(False)
        self.pushButtonStartImpedance.setObjectName("pushButtonStartImpedance")
        self.horizontalLayout_2.addWidget(self.pushButtonStartImpedance)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBoxMode, 0, 0, 1, 1)

        self.retranslateUi(frmNeoRecOnline)
        QtCore.QMetaObject.connectSlotsByName(frmNeoRecOnline)

    def retranslateUi(self, frmNeoRecOnline):
        _translate = QtCore.QCoreApplication.translate
        frmNeoRecOnline.setWindowTitle(_translate("frmNeoRecOnline", "Frame"))
        self.groupBoxMode.setTitle(_translate("frmNeoRecOnline", "Amplifier NeoRec"))
        self.pushButtonStartDefault.setText(_translate("frmNeoRecOnline", "Default\n"
"Mode"))
        self.pushButtonStop.setText(_translate("frmNeoRecOnline", "Stop"))
        self.pushButtonStartImpedance.setStyleSheet(_translate("frmNeoRecOnline", "text-align: left; padding-left: 10px;"))
        self.pushButtonStartImpedance.setText(_translate("frmNeoRecOnline", "Impedance\n"
"Mode"))

